config/routes.rb
Rails.application.routes.draw do

  
  get 'tags/:tag', to: 'topics#show', as: :tag
  get 'tags_comments/:tags_comments', to: 'comments#show', as: :tags_comments
  
  devise_for :users

  resources :users
  
  resources :posts do
    resources :comments, :only => [:create]
  end
  
  resources :forums do
    resources :topics
  end
  

  root 'forums#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics, :dependent => :destroy

	validates :name, :description, presence: true
  	validates :name, uniqueness: true
  	
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index] 
  before_filter :is_admin? , :except => :index
  skip_before_filter :verify_signed_out_user
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>

      <ul>
      <% @forum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<% if user_signed_in? && current_user.admin == true %>
  <h2>Listing forums</h2>
  <table class="table">
    <thead>
      <th width="40%">Forum</th>
      <th width="25%">Last Post</th>
      <th width="17%">Posts</th>
      <th width="20%">Links</th>
    </thead> 
    <% for forum in @forums %>
    <tbody >
      <tr class="forum_tittle">
        <td ><h4><%= link_to h(forum.name), forum_path(forum.id) %></h4>
          <small><%=h forum.description %></small></td>
          <td><h4><%= link_to "Create New Topic", new_forum_topic_path(:forum_id=> forum.id) %><h4></td>
          <td></td>
          <td class="list_actions"><%= link_to "Show", forum %>
           <%= link_to "Edit", edit_forum_path(forum) %>
           <%= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %>
         </td>
       </tr>
       <% @topics=forum.topics %>
       <% for topic in @topics %>
       <tbody class="topic_tittle">
        <tr>
          <td><%= link_to "#{topic.name}", forum_topic_path(:id=>topic.id,:forum_id=> forum.id) %></td>
          <% @post=topic.posts.order("created_at").last %>
          <% if @post==nil%>
          <td><%= "No Post Yet" %></td>
          <% else %>
          <td><%= @post.created_at %></td>
          <% end %>
          <td><%= topic.posts.count %></td>
          <td class="list_actions"><%= link_to "Show", forum %>
            <%= link_to "Edit", edit_forum_path(forum) %>
            <%= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
        </tbody>
        <% end %>
      </tbody>
      <% end %>
    </table>
    <p><h3><%= link_to "New Forum", new_forum_path %></h3></p>
<% else %>
  <h2>Listing forums</h2>
  <table class="table">
    <thead>
      <th width="60%">Forum</th>
      <th width="25%">Last Post</th>
      <th width="17%">Posts</th>
    </thead> 
    <% for forum in @forums %>
    <tbody >
      <tr class="forum_tittle">
        <td ><h4><%= link_to h(forum.name), forum_path(forum.id) %></h4>
          <small><%=h forum.description %></small>
        </td>
        <td></td>
        <td></td>
      </tr>
      <% @topics=forum.topics %>
      <% for topic in @topics %>
      <tbody class="topic_tittle">
        <tr>
          <td><%= link_to "#{topic.name}", forum_topic_path(:id=>topic.id,:forum_id=> forum.id) %></td>
          <% @post=topic.posts.order("created_at").last %>
          <% if @post==nil%>
          <td><%= "No Post Yet" %></td>
          <% else %>
          <td><%= @post.created_at %></td>
          <% end %>
          <td><%= topic.posts.count %></td>
        </tr>
      </tbody>
      <% end %>
    </tbody>
    <% end %>


  </table>
  <% end %>

app/views/forums/new.html.erb
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>