config/routes.rb
Rails.application.routes.draw do

  
  get 'tags/:tag', to: 'topics#show', as: :tag
  get 'tags_comments/:tags_comments', to: 'comments#show', as: :tags_comments
  
  devise_for :users

  resources :users
  
  resources :posts do
    resources :comments, :only => [:create]
  end
  
  resources :forums do
    resources :topics
  end
  

  root 'forums#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  has_many :posts, :dependent => :destroy
  belongs_to :users

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :forum_id, presence: true

  acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :tag_list
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :is_admin? , :except => :show
 
  def index
    if params[:tag]
      @topics = Topic.tagged_with(params[:tag])
    else
      @topics = Topic.all
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to forum_topic_path(:id=>@topic.id), notice: 'Topic was successfully created.' }
        
      else
        format.html { redirect_to new_forum_topic_path, notice: 'Topic was not successfully created.' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to forum_topic_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :last_poster_id, :last_post_at, :forum_id,:tag_list)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
<% if @topic.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

  <ul>
    <% @topic.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <% f.label :user_id %><br>
  <%= f.hidden_field :user_id, :value=> current_user.id %>
</div>


<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>


<div class="field">
  <% f.label :forum_id %><br>
  <%= f.hidden_field :forum_id, :value=> @forum.id %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
     <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
		<td><%= raw topic.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back',forums_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @topic.name %></h2>
<p>Tags: <%= raw @topic.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
<table class="table">
	<thead>
		<th width="60%">Post</th>
		<th width="25%">Last Comment</th>
		<th width="17%">Comments</th>
	</thead> 	
	<% @posts=@topic.posts %>
	<% for post in @posts %>
	<tbody class="post_tittle">
		<tr>
			<td><%= link_to "#{post.title}", post %></td>
			<% @comment=post.comments.order("created_at").last %>
			<% if @comment==nil%>
				<td><%= "No Comment Yet" %></td>
			<% else %>
				<td><%= @comment.created_at %></td>
			<% end %>
			<td><%= post.comments.count %></td>
		</tr>
	</tbody>
	<% end %>
	<tr><%= link_to 'New Post', new_post_path(:topic_id=>@topic.id)%><tr>
</table>